modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/ShyNieke/StatuesMod/issues"
license="MIT"

[[mods]]
modId="statues"
version="${file.jarVersion}"
displayName="Statues Mod"
displayURL="https://minecraft.curseforge.com/projects/statues"
authors="ShyNieke, Mrbysco"
description='''
Just a little functional decoration.
'''
[[dependencies.statues]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.statues]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.167,)"
ordering="NONE"
side="BOTH"